### ISSUE TITLE
Plugin fails to load on OpenClaw 2026.4.5: Cannot find module 'root-alias.cjs/discord'

### ISSUE THREAD

**Issue by PDiTO** [pwrdrvr/openclaw-codex-app-server#84]
## Environment

  - OpenClaw: 2026.4.5 (3e72c03)
  - Plugin: openclaw-codex-app-server@0.6.0 (also affects 0.5.0)
  - Platform: macOS (Darwin 25.3.0, arm64)
  - Node: v24.14.1

  ## Error

  Plugin fails to load on startup:

  openclaw-codex-app-server failed to load from ~/.openclaw/extensions/openclaw-codex-app-server/index.ts:
  Error: Cannot find module '/Users/pdito/.nvm/versions/node/v24.14.1/lib/node_modules/openclaw/dist/plugin-sdk/root-alias.cjs/discord'
  Require stack:
  - /Users/pdito/.openclaw/extensions/openclaw-codex-app-server/src/controller.ts

  ## Cause

  The plugin imports `root-alias.cjs/discord` as a subpath, but as of OpenClaw 2026.4.5, `plugin-sdk/root-alias.cjs` is a single file rather than a directory with subpath exports.
   This appears to be a plugin SDK breaking change.

  Worked on 2026.4.1, broke on 2026.4.2+.

  ## Steps to reproduce

  1. Install OpenClaw 2026.4.5
  2. `openclaw plugins install openclaw-codex-app-server@0.6.0 --dangerously-force-unsafe-install`
  3. `openclaw gateway restart`
  4. Check logs — plugin fails to initialize
