### PR TITLE
Plugin: use structural types for plugin-sdk subpath modules

### LINKED ISSUE #84: Plugin fails to load on OpenClaw 2026.4.5: Cannot find module 'root-alias.cjs/discord'
## Environment

  - OpenClaw: 2026.4.5 (3e72c03)
  - Plugin: openclaw-codex-app-server@0.6.0 (also affects 0.5.0)
  - Platform: macOS (Darwin 25.3.0, arm64)
  - Node: v24.14.1

  ## Error

  Plugin fails to load on startup:

  openclaw-codex-app-server failed to load from ~/.openclaw/extensions/openclaw-codex-app-server/index.ts:
  Error: Cannot find module '/Users/pdito/.nvm/versions/node/v24.14.1/lib/node_modules/openclaw/dist/plugin-sdk/root-alias.cjs/discord'
  Require stack:
  - /Users/pdito/.openclaw/extensions/openclaw-codex-app-server/src/controller.ts

  ## Cause

  The plugin imports `root-alias.cjs/discord` as a subpath, but as of OpenClaw 2026.4.5, `plugin-sdk/root-alias.cjs` is a single file rather than a directory with subpath exports.
   This appears to be a plugin SDK breaking change.

  Worked on 2026.4.1, broke on 2026.4.2+.

  ## Steps to reproduce

  1. Install OpenClaw 2026.4.5
  2. `openclaw plugins install openclaw-codex-app-server@0.6.0 --dangerously-force-unsafe-install`
  3. `openclaw gateway restart`
  4. Check logs — plugin fails to initialize

### PR DESCRIPTION
**Pull request by PDiTO**
## Summary

- Replace `typeof import("openclaw/plugin-sdk/discord")` type aliases with equivalent structural interface types
- jiti resolves those `import()` expressions at load time, which fails on OpenClaw >=2026.4.2 where the subpath exports were removed — the plugin crashes before the runtime compat fallback added in #83 can run
- The runtime loading via `loadOpenClawCompatModule` was already correct; this fix ensures the file can be parsed/loaded in the first place

Fixes #84

## Test plan

- [x] `pnpm typecheck` passes
- [x] `pnpm test` — all controller and compat tests pass (1 pre-existing locale-dependent failure in `format.test.ts` unrelated to this change)

### CODE REVIEW

**Comment by huntharo** [comment]
I have been trying this with 2026.4.5 but it didn't resolve the ability to use the plugin in Discord for me.  I get the same result: 1. on an official install a `/cas_resume` responds but with no buttons 2. on a `main` install of openclaw the plugin works with Discord, until a recent change in the last couple hours that caused it to break completely

**Comment by PDiTO** [comment]
Are you using the stable build of Openclaw or the dev channel?

**Comment by huntharo** [comment]
> Are you using the stable build of Openclaw or the dev channel?

I tested both as noted. The stable build doesn't work. Main also doesn't work but because of a different reason.

I think we are going to have to finish the generic interface and move the plugin to than. There is just too much churn on the interface right now.
